name: Deploy cloud run service
on:
  push:
    branches:
      - "master"
env:
  PROJECT_ID: ${{secrets.PROJECT_ID}}
  RUN_REGION: us-central1
  SERVICE_NAME: cloud-run-base

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: $PROJECT_ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud auth configure-docker
      - uses: devmasx/cached-docker-build-push@v0.1.1
        with:
          image_name: gcr.io/$PROJECT_ID/$SERVICE_NAME
          build_params: --build-arg=NPM_TOKEN=${{secrets.NPM_TOKEN}}
      - run: |
          gcloud run deploy $SERVICE_NAME \
            --project $PROJECT_ID \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME \
            --platform managed \
            --region $RUN_REGION \
            --set-env-vars=NODE_ENV=production


#  --vpc-connector projects/$PROJECT_ID/locations/$RUN_REGION/connectors/$redis--SERVICE_NAME \
